config/routes.rb
Rails.application.routes.draw do
  resources :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees =  Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end
  def create
    @employee = Employee.new(employee_params)
    if  @employee.save
      redirect_to employees_path
    else
      render :new
    end
  end
  def edit
    @employee = Employee.find(params[:id])
  end
  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render :edit

  end
end
def destroy
  @employee = Employee.find(params[:id])
  @employee.destroy
  redirect_to employees_path

end
  private
    def employee_params
      params.require(:employee).permit(:name, :age, :gender, :designation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/edit.html.erb
<%= form_for @employee do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label :age %>
  <%= f.number_field :age %>
</div>
<div>
  <%= f.label :gender %>
  <%= f.text_field :gender %>
</div>
<div>
  <%= f.label :designation %>
  <%= f.text_field :designation %>
</div>
<div>
  <%= f.submit %>
</div>
<% end %>

app/views/employees/index.html.erb
<h1>Details of Employee</h1>
      <%= link_to "Create", new_employee_path %>
<table>
  <thead>
    <th>Name</th>
    <th>Age</th>
    <th>Gender</th>
    <th>Designation</th>
  </thead>
<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= employee.age %></td>
    <td><%= employee.gender %></td>
    <td><%= employee.designation %></td>
    <td>

      <%= link_to "Edit", edit_employee_path(employee) %>
      <%= link_to "Delete", employee, method: :delete, data: {confirm: "Are you sure you want to delete employee details?"} %>
    </td>
  </tr>
  <% end %>
</table>

app/views/employees/new.html.erb
<%= form_for @employee do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label :age %>
  <%= f.number_field :age %>
</div>
<div>
  <%= f.label :gender %>
  <%= f.text_field :gender %>
</div>
<div>
  <%= f.label :designation %>
  <%= f.text_field :designation %>
</div>
<div>
  <%= f.submit %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>